/**
 * YouTube Transcript Extraction Module
 * Uses youtube-caption-extractor for reliable transcript fetching
 */

import { getSubtitles } from 'youtube-caption-extractor'

export interface TranscriptSegment {
  text: string;
  start: number; // Start time in seconds
  duration: number; // Duration in seconds
}

export interface VideoMetadata {
  title: string;
  channelName: string;
  channelId?: string;
  description?: string;
  uploadDate?: string;
  viewCount?: string;
  likeCount?: string;
  duration?: string;
  videoThumbnail?: string;
}

export interface TranscriptResult {
  success: boolean;
  transcript?: TranscriptSegment[];
  videoId?: string;
  videoTitle?: string;
  videoThumbnail?: string;
  metadata?: VideoMetadata;
  language?: string;
  isAutoGenerated?: boolean;
  error?: string;
}

/**
 * Get video ID from current URL
 */
function getVideoIdFromUrl(): string | null {
  const urlParams = new URLSearchParams(window.location.search);
  return urlParams.get('v');
}

/**
 * Extract video metadata directly from DOM elements
 * This is the most reliable method during YouTube's SPA navigation
 */
function extractVideoMetadataFromDOM(): VideoMetadata | null {
  console.log('[VidChat Debug] === Extracting Video Metadata from DOM ===');
  
  try {
    const titleElement = document.querySelector('h1.ytd-video-primary-info-renderer yt-formatted-string, h1.ytd-watch-metadata yt-formatted-string');
    const channelElement = document.querySelector('ytd-channel-name a, #channel-name a');
    const descriptionElement = document.querySelector('ytd-expandable-video-description-body-renderer, #description-inner');
    
    const title = titleElement?.textContent?.trim();
    const channelName = channelElement?.textContent?.trim();
    const description = descriptionElement?.textContent?.trim();
    
    console.log('[VidChat Debug] DOM - Title element found:', !!titleElement);
    console.log('[VidChat Debug] DOM - Title:', title);
    console.log('[VidChat Debug] DOM - Channel:', channelName);
    
    if (!title || title === '') {
      console.log('[VidChat Debug] ❌ No title found in DOM');
      return null;
    }
    
    console.log('[VidChat Debug] ✅ Successfully extracted metadata from DOM');
    return {
      title,
      channelName: channelName || 'YouTube',
      description: description || '',
    };
  } catch (error) {
    console.log('[VidChat Debug] ❌ Error extracting from DOM:', error);
    return null;
  }
}

/**
 * Format duration in seconds to human-readable format
 */
function formatDuration(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;
  
  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${minutes}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Extract video metadata with retry logic for DOM elements
 * Retries with delays to give YouTube's SPA time to update the DOM
 */
async function extractVideoMetadataWithRetry(expectedVideoId: string, maxRetries = 3): Promise<VideoMetadata | null> {
  console.log('[VidChat Debug] === Extracting Video Metadata (with retry) ===');
  console.log('[VidChat Debug] Expected VideoId:', expectedVideoId);
  
  for (let attempt = 0; attempt < maxRetries; attempt++) {
    if (attempt > 0) {
      console.log(`[VidChat Debug] Retry attempt ${attempt + 1}/${maxRetries}...`);
      // Wait between retries to let YouTube's SPA update the DOM
      await new Promise(resolve => setTimeout(resolve, 500));
    }
    
    const metadata = extractVideoMetadataFromDOM();
    
    if (metadata && metadata.title && metadata.title !== '') {
      console.log('[VidChat Debug] ✅ Successfully extracted metadata');
      return metadata;
    }
    
    console.log('[VidChat Debug] DOM not ready yet or no title found, will retry...');
  }
  
  // All retries exhausted - return minimal metadata
  console.log('[VidChat Debug] ⚠️ All retry attempts exhausted, returning minimal metadata');
  return {
    title: 'Video',
    channelName: 'YouTube',
    description: '',
  };
}

/**
 * Main function to extract transcript for current YouTube video
 * Uses youtube-caption-extractor library for reliable fetching
 * Now with retry logic for metadata extraction during SPA navigation
 */
export async function extractVideoTranscript(): Promise<TranscriptResult> {
  try {
    const videoId = getVideoIdFromUrl();
    console.log('[VidChat Debug] ====================================');
    console.log('[VidChat Debug] STARTING TRANSCRIPT EXTRACTION');
    console.log('[VidChat Debug] URL VideoId:', videoId);
    console.log('[VidChat Debug] ====================================');
    
    if (!videoId) {
      return {
        success: false,
        error: 'No video ID found in URL',
      };
    }

    console.log('[VidChat Debug] Fetching subtitles from YouTube API for videoId:', videoId);
    const subtitles = await getSubtitles({ videoID: videoId, lang: 'en' });
    
    if (!subtitles || subtitles.length === 0) {
      return {
        success: false,
        error: 'No captions available for this video',
      };
    }

    console.log('[VidChat Debug] ✅ Subtitles fetched successfully, segments:', subtitles.length);

    const transcript: TranscriptSegment[] = subtitles.map((sub: any) => ({
      text: sub.text,
      start: sub.start,
      duration: sub.dur || 0,
    }));

    // Use retry logic to wait for YouTube's SPA to update metadata
    console.log('[VidChat Debug] Extracting metadata with retry logic...');
    const metadata = await extractVideoMetadataWithRetry(videoId);

    const result = {
      success: true,
      transcript,
      videoId,
      videoTitle: metadata?.title || 'Video',
      videoThumbnail: metadata?.videoThumbnail,
      metadata: metadata ?? undefined,
      language: 'en',
      isAutoGenerated: true,
    };

    console.log('[VidChat Debug] ====================================');
    console.log('[VidChat Debug] FINAL RESULT:');
    console.log('[VidChat Debug] VideoId:', result.videoId);
    console.log('[VidChat Debug] VideoTitle:', result.videoTitle);
    console.log('[VidChat Debug] Metadata Title:', result.metadata?.title);
    console.log('[VidChat Debug] VideoId matches metadata:', result.videoId === videoId ? '✅ CORRECT' : '❌ MISMATCH');
    console.log('[VidChat Debug] ====================================');

    return result;
  } catch (error) {
    console.log('[VidChat Debug] ❌ ERROR in extractVideoTranscript:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}
