/**
 * YouTube Transcript Extraction Module
 * Uses youtube-caption-extractor for reliable transcript fetching
 */

import { getSubtitles } from 'youtube-caption-extractor'

export interface TranscriptSegment {
  text: string;
  start: number; // Start time in seconds
  duration: number; // Duration in seconds
}

export interface VideoMetadata {
  title: string;
  channelName: string;
  channelId?: string;
  description?: string;
  uploadDate?: string;
  viewCount?: string;
  likeCount?: string;
  duration?: string;
  videoThumbnail?: string;
}

export interface TranscriptResult {
  success: boolean;
  transcript?: TranscriptSegment[];
  videoId?: string;
  videoTitle?: string;
  videoThumbnail?: string;
  metadata?: VideoMetadata;
  language?: string;
  isAutoGenerated?: boolean;
  error?: string;
}

/**
 * Get video ID from current URL
 */
function getVideoIdFromUrl(): string | null {
  const urlParams = new URLSearchParams(window.location.search);
  return urlParams.get('v');
}

/**
 * Extract ytInitialPlayerResponse from the YouTube player API
 */
function extractYouTubePlayerResponse(): any | null {
  try {
    // Method 1: Use the player API (most reliable)
    const player = document.querySelector('#movie_player') as any;
    
    if (player && typeof player.getPlayerResponse === 'function') {
      try {
        const response = player.getPlayerResponse();
        if (response) {
          return response;
        }
      } catch (e) {
        // Failed to get player response from API
      }
    }
    
    // Method 2: Look for ytInitialPlayerResponse in script tags (fallback)
    const scripts = document.querySelectorAll('script');
    
    for (const script of scripts) {
      const content = script.textContent || '';
      const match = content.match(/var ytInitialPlayerResponse\s*=\s*({.+?});/s);
      if (match) {
        try {
          return JSON.parse(match[1]);
        } catch (e) {
          // Failed to parse ytInitialPlayerResponse
        }
      }
    }

    // Method 3: Check if it's available on window object (fallback)
    if ((window as any).ytInitialPlayerResponse) {
      return (window as any).ytInitialPlayerResponse;
    }

    return null;
  } catch (error) {
    return null;
  }
}

/**
 * Format duration in seconds to human-readable format
 */
function formatDuration(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;
  
  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${minutes}:${secs.toString().padStart(2, '0')}`;
}

/**
 * Extract video metadata from YouTube page
 */
function extractVideoMetadata(): VideoMetadata | null {
  try {
    const playerResponse = extractYouTubePlayerResponse();
    
    if (playerResponse?.videoDetails) {
      const details = playerResponse.videoDetails;
      
      return {
        title: details.title || 'Unknown Title',
        channelName: details.author || 'Unknown Channel',
        channelId: details.channelId,
        description: details.shortDescription || '',
        viewCount: details.viewCount || '0',
        duration: details.lengthSeconds ? formatDuration(parseInt(details.lengthSeconds)) : undefined,
        videoThumbnail: details.thumbnail?.thumbnails?.[0]?.url,
      };
    }
    
    // Fallback: Try to extract from page elements
    const titleElement = document.querySelector('h1.ytd-video-primary-info-renderer yt-formatted-string, h1.ytd-watch-metadata yt-formatted-string');
    const channelElement = document.querySelector('ytd-channel-name a, #channel-name a');
    const descriptionElement = document.querySelector('ytd-expandable-video-description-body-renderer, #description-inner');
    
    return {
      title: titleElement?.textContent?.trim() || 'Unknown Title',
      channelName: channelElement?.textContent?.trim() || 'Unknown Channel',
      description: descriptionElement?.textContent?.trim() || '',
    };
  } catch (error) {
    return null;
  }
}

/**
 * Main function to extract transcript for current YouTube video
 * Uses youtube-caption-extractor library for reliable fetching
 */
export async function extractVideoTranscript(): Promise<TranscriptResult> {
  try {
    const videoId = getVideoIdFromUrl();
    
    if (!videoId) {
      return {
        success: false,
        error: 'No video ID found in URL',
      };
    }

    const subtitles = await getSubtitles({ videoID: videoId, lang: 'en' });
    
    if (!subtitles || subtitles.length === 0) {
      return {
        success: false,
        error: 'No captions available for this video',
      };
    }

    const transcript: TranscriptSegment[] = subtitles.map((sub: any) => ({
      text: sub.text,
      start: sub.start,
      duration: sub.dur || 0,
    }));

    const metadata = extractVideoMetadata();

    return {
      success: true,
      transcript,
      videoId,
      videoTitle: metadata?.title || 'Unknown Video',
      videoThumbnail: metadata?.videoThumbnail,
      metadata: metadata ?? undefined,
      language: 'en',
      isAutoGenerated: true,
    };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}
